### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#1]
The current logo is OK but it would be nice to have something a lot simpler. It was created with an SVG I purchased which was modified with illustrator and the lines smoothed out and color with shading added.

**Comment by sejr** [comment]
![](https://i.imgur.com/MTAJSCu.png)
![](https://i.imgur.com/vooxypr.png)
![](https://imgur.com/HF6fofp.png)

[Galea SVG source](https://www.svgrepo.com/svg/71032/roman-helmet)

**Comment by fredericbonnet** [comment]
I was about to open an issue about the logo :)

The current logo is a Greek helmet, not a Roman one. The logo proposed by @sejr is correct.

I like the middle design BTW.

**Comment by kimstacy** [comment]
@sejr What are your thoughts on a laurel wreath? Is the Roman helmet a cemented desire?

Example of what I mean: 
![spqr](https://user-images.githubusercontent.com/46656072/75425197-d5830c80-5907-11ea-99f1-21c93f5f7a96.png)

[Source](https://en.wikipedia.org/wiki/SPQR#/media/File:Roman_SPQR_banner.svg) 

---
I also discovered a more simplistic rendition at the site linked above. See [here](https://www.pngrepo.com/svg/276848/helmet-armor).

![svgrepo](https://user-images.githubusercontent.com/46656072/75425350-25fa6a00-5908-11ea-82bb-fa9dcc43fed6.png)

**Comment by MaggieAppleton** [comment]
👋 If you need some help with this, I'm up for it.

I'm the AD/illustrator for egghead and have some experience with tech logos 👉 
 https://maggieappleton.com/

For branding projects I like the approach of have a well illustrated graphic for website headers and promotions (stickers, podcast covers, etc.), and then a matching simplified SVG for small-scale menu bars, favicons, etc. Gives you a good range across all future use cases.

Just to help explain the tactic, here's a simple/complex pair I did for [Pure React](https://purereact.com/):

![image](https://user-images.githubusercontent.com/5599295/75426445-93c08900-593c-11ea-8c62-ce46987bf9a1.png)
![image](https://user-images.githubusercontent.com/5599295/75426304-50661a80-593c-11ea-8502-f4022cbb88e6.png)

**Comment by sgwilym** [comment]
Given the namesake:

> Rome gets its name from proverbs such as "All Roads Lead to Rome", "Rome wasn't built in a day" and "When in Rome, do as the Romans do". This refers to the expansive scope and the desire for conformity across the project. It started as a joke at the office.

A focus on militaristic imagery seems off-key. To me it makes sense to somehow symbolise Rome's fixation on infrastructure and their engineering feats.

Imagery like an aqueduct, maybe? It represents infrastructure well, has a pleasing internal visual rhythm, and has a great silhouette:

![image](https://user-images.githubusercontent.com/579491/75432979-8b257e00-594f-11ea-8220-89603757d90e.png)

![My Sketches 9 - 2020-02-27 10 46 00](https://user-images.githubusercontent.com/579491/75432818-4d285a00-594f-11ea-9d40-20242289e834.jpg)

(err... please don't judge me by the sketch above -- just think it's better to think in rough sketches so early on).

**Comment by iraycd** [comment]
@MaggieAppleton I think it's great, but I personally prefer square than rectangular logos.

**Comment by sebmck** [comment]
Thanks for the logo designs everyone! I've had a few other people privately reach out so I'll wait for any additional contributions and we can make a decision in a few weeks.

@fredericbonnet

> I was about to open an issue about the logo :) The current logo is a Greek helmet, not a Roman one.

We are aware. The [README](https://github.com/facebookexperimental/rome#history) explicitly mentions this:

> Rome has a logo of an ancient Greek spartan helmet. It's not very relevant since it's not Roman, but it looks cooler than a Galea.

**Comment by matiasngf** [comment]
I found @sgwilym idea interesting..., so I tried to made something based on that: 

![Rome-Logo](https://user-images.githubusercontent.com/29680544/75487605-75cf4480-598d-11ea-9470-e16febc43d89.jpg)

**Comment by sebmck** [comment]
The helmet isn't important to keep at all. In fact I'd strongly be in favor of getting rid of it.

**Comment by Jeffersonchive** [comment]
> A focus on militaristic imagery seems off-key. To me it makes sense to somehow symbolise Rome's fixation on infrastructure and their engineering feats.

I think this is the ticket, as recent criticisms have highlighted its vulnerability to alluding to Rome's violent past and all it entails. While I disagree with that interpretation within the context of this project, it would be doubtlessly beneficial to not provide an inch of argumentative grounds within the logo as well. Rome was an Empire that was profoundly interested in art and constructs; I can think of no better symbol for this that is uniquely "Roman" than the composite order of columns. 

![image](https://user-images.githubusercontent.com/1173827/75496803-54238c80-5990-11ea-81b8-878f60c1cb1f.png)


Why is this a great idea? It's a functional weight-bearing element of some of Europe's most prized historical structures. People seem to think it's beautiful. Getting the right one in your logo also shows that you've done thoughtful research. It also draws inspiration from Egyptian and Greek architecture, which is to say that it reaches to other cultures to make something new and great. Not only is it without inference to violence, it is with inference to **structure, beauty, tradition, and cosmopolitanism**.  

I'll dust off my InkScape and see what I can do in terms of a tasteful and memorable logo - in the meantime, let me know what the core principles of what your logo's message should be and I'll likewise try to incorporate them.

**Comment by binarybaba** [comment]
Can have an aerial view of the colloseum. Gives you a circular subtle base which fits on a square.
Just food for thought for designers.

![image](https://user-images.githubusercontent.com/6381439/75591783-eefb9400-5a80-11ea-98dd-d6836226f607.png)
![image](https://user-images.githubusercontent.com/6381439/75591911-48fc5980-5a81-11ea-8317-dbcf3af7f143.png)

**Comment by jonasgrilleres** [comment]
> Given the namesake:
> 
> > Rome gets its name from proverbs such as "All Roads Lead to Rome", "Rome wasn't built in a day" and "When in Rome, do as the Romans do". This refers to the expansive scope and the desire for conformity across the project. It started as a joke at the office.
> 
> A focus on militaristic imagery seems off-key. To me it makes sense to somehow symbolise Rome's fixation on infrastructure and their engineering feats.
> 
> Imagery like an aqueduct, maybe? It represents infrastructure well, has a pleasing internal visual rhythm, and has a great silhouette:
> 
> ![image](https://user-images.githubusercontent.com/579491/75432979-8b257e00-594f-11ea-8220-89603757d90e.png)
> 
> ![My Sketches 9 - 2020-02-27 10 46 00](https://user-images.githubusercontent.com/579491/75432818-4d285a00-594f-11ea-9d40-20242289e834.jpg)
> 
> Though I realise the above also looks a bit like the coliseum.
> 
> (err... please don't judge me by the sketch above -- just think it's better to think in rough sketches so early on).

I think the Colosseum represents Rome even better. Viaducts would be great for a devops/infrastructure project :) 

I like the analogy between the robust architectural structure and the purpose of this new toolchain 👍

**Comment by lucagentile** [comment]
> I was about to open an issue about the logo :)
> 
> The current logo is a Greek helmet, not a Roman one. The logo proposed by @sejr is correct.
> 
> I like the middle design BTW.

Agree. Praetorian helmets are cool, no need to use a Greek's one.
As other people suggested, there are also other things from Roman civilization to use as inspiration. So why use something historically inaccurate?

https://www.google.com/search?q=roman+civilization+vector&tbm=isch&ved=2ahUKEwiV14SB7oboAhUFLOwKHWGdCrwQ2-cCegQIABAA&oq=roman+civilization+vector&gs_l=img.3...6559.8704..8758...0.0..0.105.481.5j1......0....1..gws-wiz-img.......0i19.XcA8tJAC3yQ&ei=kMliXpXPHoXYsAfhuqrgCw&bih=876&biw=1680

**Comment by aarjithn** [comment]
The phrase "all roads lead to Rome" is a reference to the Milliarium Aureum—the point to which all roads were said to lead. This is the remains of the same. There are couple of interesting symbols here - could this be simplified and used as logo?

![image](https://user-images.githubusercontent.com/10304259/76488696-318f7a00-644c-11ea-8734-8faef6a98e2b.png)

**Comment by andreadito** [comment]
please change the logo!

**Comment by sebmck** [comment]
Wanted to resurrect this issue since I'd be amazing to have a finalized logo for when we have a release to really cement the project from the beginning.

I really like the laurel wreath idea (suggested by @kimstacy) and the Milliarium Aureum symbols (suggested by @aarjithn) also look really interesting.

I think we definitely don't want something like a helmet, spear etc. I think it would be interesting to invoke more classical elements which would let us theme the website in a lot of interesting ways, eg. having illustrations on the website in a classical style.

I would expect the logo to define the color scheme and style of the website. Possibly incorporating a shade of "JavaScript Yellow", ie. [unofficial JS logo](https://github.com/voodootikigod/logo.js) and [Babel](https://github.com/babel/logo/blob/master/babel.png).

**Comment by EduardoLopes** [comment]
Let's see. I'm up do this.

Before start to working on the logo idea i made this to try to capture a mood, see shapes and try a color palette. On this one i tried the "javascript yellow", as you said above.

![Yellow](https://user-images.githubusercontent.com/1084297/80420988-14a2ef00-88b2-11ea-861e-f1b26b3ac55e.png)

On this one i tried a color palette going more towards the Rome flag colors.

![Rome Scapes - flag](https://user-images.githubusercontent.com/1084297/80421427-dce87700-88b2-11ea-98cc-0f1844d0e70e.png)

Looking forward on the feedback on these, to see if i'm in the right track.  I'll start to work on the logo and come back with some ideas.

**Comment by EduardoLopes** [comment]
Just to update. I'm still working on this, but not ready to post just yet.

**Comment by EduardoLopes** [comment]
I finally finished. It's a logo inspired by the arch in the romam architecture, the arch is all over the place in their constructions and it's pretty important. The shape of the arch is more clear when you see it in the pattern, with the logo repeated. 

The yellow used is the one in the rome flag. I can try others colors if necessary!

I hope the community like it!

![01 - Rome - Logo Mark](https://user-images.githubusercontent.com/1084297/81314915-0c8c4180-9060-11ea-9722-2e1f05bab336.jpg)
![02 - Rome - Logo Type](https://user-images.githubusercontent.com/1084297/81314919-0e560500-9060-11ea-9a5b-3a384ecd4a2e.jpg)
![03 - Rome - Darkbackgrond](https://user-images.githubusercontent.com/1084297/81314925-0f873200-9060-11ea-9769-a9f8d097c41a.jpg)
![04 - Rome - Inspirations](https://user-images.githubusercontent.com/1084297/81314928-101fc880-9060-11ea-9ca9-ad8e4523f742.jpg)
![05 - Rome - Pattern](https://user-images.githubusercontent.com/1084297/81314931-1150f580-9060-11ea-8024-6b6d2154a18e.jpg)
![06 - Rome - Font](https://user-images.githubusercontent.com/1084297/81314933-11e98c00-9060-11ea-9934-4a373b35174c.jpg)
![07 - Rome - ASCII](https://user-images.githubusercontent.com/1084297/81314937-131ab900-9060-11ea-8f46-5b14bd663aeb.jpg)
![08 - Rome - Sizes](https://user-images.githubusercontent.com/1084297/81314939-13b34f80-9060-11ea-8a52-5f3e12114873.jpg)
![09 - Rome - Colors](https://user-images.githubusercontent.com/1084297/81314942-13b34f80-9060-11ea-8ea4-97dd8adbf320.jpg)

**Comment by lucagentile** [comment]
It's cool! Really like it.

Black definitely gives a more modern look.
Common colors in ancient Rome are purple (the Senate), green, white, gold,
blue, and obviously red.
I don't think is that kind of necessary to have *everything* in a logo
related to Rome, there are already plenty of references on that logo and
the idea doesn't convince me. Some modern vibe is appreciated.
I would try only another shade of gold or blue\*caerelum* (that also
reminds water?).

Great.

Il giorno gio 7 mag 2020 alle ore 17:53 Eduardo Lopes <
notifications@github.com> ha scritto:

**Comment by sebmck** [comment]
Wow nice! I like it. It looks awesome as a pattern. I asked a few people for their thoughts and this was some of the more critical comments:

> first reaction is it looks like a college or university logo
> after reading the inspiration i like it a lot more
> Yeah I was just saying the yellow and dark gray feels very enterprisey to me, but I don't mind the white on dark gray
> you know what it actually reminds me of? It looks like a mandalorian helmet straight forward
> looks like a car brand like Tesla
> it looks great as a pattern
> without any context you don't know what it is and i assumed it was like ram horns or something
> It's super yonic

**Comment by jamiebuilds** [comment]
So personally I think we should avoid doubling down on Rome imagery, because I don't think we should be trying to invoke the literal _"Rome: The City"_. We're trying to invoke _"Rome: The Tool"_.

I think we should take a step back and ask what we want out of Rome's identity:

- Bold
- Stable
- Exciting
- etc.

And then we should look for inspiration out of what Rome is actually doing:

- Converging many different tools into one
- Hitting the reset button on the JavaScript ecosystem
- Improving developer experience
- etc.

"Rome: The Place" should a lower priority thing that we only integrate if we can do so in a clever way.

Otherwise it's gonna keep feeling like we're forcing _"Rome: The Place"_ onto the something that has little to do with it.

**Comment by sebmck** [comment]
Honestly the more I research and read the history of Ancient Rome I'm having more difficulty wanting to invoke the memories and comparison.

**Comment by EduardoLopes** [comment]
@lucagentile 
Yeah, i was going for something modern. I stick to yellow because @sebmck mentioned above, but i don't think the js logo yellow fits well in this logo, so i prefere to use the yellow from the rome flag. And use blue to remind water is cool, since the arch was heavily used in the aqueducts as well.

Here's other colors: 
![Other Colors](https://user-images.githubusercontent.com/1084297/81357786-f8216680-90aa-11ea-8c49-99d5699d2adb.jpg)
(3 is the yellow from the JS logo)

---
@sebmck 

This is good feedback. Now i can't unseen the car brand. But, i don't think it looks yonic (learned this word today), but i'd agree it looks a bit like a womb/uterus. When i designed it, i tried to see others shapes, this didn't came to my mind, but i see a "T" and horns as well. 

I didn't want the logo to have a obvious shape of an arch like the image below. Split the arch in half and realize it would works great for a pattern, got me excited.
![Artboard 12](https://user-images.githubusercontent.com/1084297/81358922-35d3be80-90ae-11ea-9ee5-1c2144cb3ace.jpg)

---
@jamiebuilds

Even though i agree with you, when you say we should think less about Rome: The Place and more about what the tool is actually doing, i think the arch concept fits well Rome, since it changed, for the better, how Romans build structures. 

It's easier to extract shapes from architecture, that's why i was going for that (and most suggestions were related to architecture as well).

From the inspirations you said, the only one i can think of any shape is:

> Converging many different tools into one

A box or square or something that holds things inside (this being Rome), and shapes inside this, representing the tools inside Rome

> Hitting the reset button on the JavaScript ecosystem

I have shape ideas from this, because of the "button" word, but i think It's too abstract for a logo.

I'll think more about these

**Comment by EduardoLopes** [comment]
Definitely there's room to improve the logomark/symbol! No comments on the logotype/font, then we can keep that. We're half way there.

I'm here to try new ideas and see if it works. Feedback is pretty important, so i know where to go. I was in a dark room with a candle trying to find stuff, now the light is on (it's low light, though) haha

---
Here's some explorations i did over the arch concept! When looking for shapes, i try even the silly ideas, so, don't mind that.
![Rome Arch Exploration](https://user-images.githubusercontent.com/1084297/81362624-a4694a00-90b7-11ea-8ad7-1b56cb97506a.jpg)

**Comment by EduardoLopes** [comment]
I just made this logo compilation so it can bring some insights to mind!

![js logos](https://user-images.githubusercontent.com/1084297/81367657-3c6d3080-90c4-11ea-88a7-abb1a60cfb4c.jpg)

**Comment by fredericbonnet** [comment]
Rome is a toolchain, right? So how about taking inspiration from Roman engineering tools, such as the Roman crane? Here is an example of such a crane used to build an aqueduct. I think that's an idea worth trying.

https://www.quora.com/How-did-the-Romans-lift-the-30-foot-high-pillars-on-to-the-foundation
![image](https://user-images.githubusercontent.com/11368533/81450530-e8755100-9182-11ea-8fa7-8a5a23883ca1.png)

**Comment by sebmck** [comment]
@EduardoLopes 

> I didn't want the logo to have a obvious shape of an arch like the image below, it's too simple. Split the arch in half and realize it would works great for a pattern, got me excited.
>
> ![logo](https://user-images.githubusercontent.com/1084297/81358922-35d3be80-90ae-11ea-9ee5-1c2144cb3ace.jpg)

Oh awesome, I prefer this logo a lot more than the T. I've shown it to a few people and so far they've agreed. I think it could be improved by maybe thickening up the lines since there's a lot of whitespace in the middle. If the pattern is useful then we could definitely still use the T logo for it since it's close enough to this one. What do you think?

Thanks for sharing the other sketches, it's great to see the evolution. @jamiebuilds pointed out that the all caps ROME looks like a fashion brand but the current Rome text you've got looks great. The serif font definitely lends well to it, and I can't think of another project logo that uses a serif font so it's definitely unique.

**Comment by ljharb** [comment]
Somewhat related, please express all copyright years in Roman numerals, so the branding is cohesive.

**Comment by jamiebuilds** [comment]
<img width="592" alt="Screen Shot 2020-05-08 at 2 33 13 PM" src="https://user-images.githubusercontent.com/952783/81451317-13d34e00-9139-11ea-8e69-ddaf51d3e466.png">

I would like to play around more with the weight and detail to make it feel more substantive

**Comment by sebmck** [comment]
I asked for some feedback on [Twitter](https://twitter.com/sebmck/status/1258874898220380160) and a lot of people seem to feel that the T logo resembles a helmet (I don't see it).

**Comment by rickhanlonii** [comment]
If you want to make the arch feel more substantive you could add a keystone, romans were the first to start using keystones and Rome is sort of the keystone of your infra.

**Comment by ljharb** [comment]
@sebmck specifically, it looks like the *shadow* part of a helmet - i think the form is called "chiaroscuro"?

**Comment by EduardoLopes** [comment]
The reflected version is discarded for me. The arch is not clear that way. People sees all sorts of things, but not a arch. The pattern created by the logo is cooler than the logo, that's not right!

I had the keystone idea while finishing that one, but decided i would try if that one was rejected. I think it looks nice!

I think the diagonal lines make it looks a bit like a helmet, so i remove it!

Here's more iterations: 
![arch explorations](https://user-images.githubusercontent.com/1084297/81458573-6b8dab80-9171-11ea-8397-5b437f89b8fb.jpg)

**Comment by orta** [comment]
Just wanted to say I like this black & orange theme, and these arch shapes feel real night

**Comment by sebmck** [comment]
Woah sweet. I really like the second and third row. Notably the last two of row three.

**Comment by EduardoLopes** [comment]
> Woah sweet, they look great. I really like the second and third row. Notably the last two of row three.

I like those too

---
Here's with sans-serif fonts
![Sans-serif](https://user-images.githubusercontent.com/1084297/81460520-4a7e8800-917c-11ea-9292-1cc04d38e097.jpg)

**Comment by EduardoLopes** [comment]
I'm sure about two things:
- "Rome" needs to be align with the bottom of the logomark, not the middle
- I like smooth edges better

**Comment by EduardoLopes** [comment]
by the way

![extra bold](https://user-images.githubusercontent.com/1084297/81460781-ed83d180-917d-11ea-9634-915af0be35ad.jpg)

**Comment by EduardoLopes** [comment]
![exploration](https://user-images.githubusercontent.com/1084297/81462572-e9f64780-9189-11ea-93a4-0abd6620defc.jpg)

**Comment by sebmck** [comment]
@EduardoLopes 

I love the fourth one "smooth edges Biryani Black", it's definitely my favourite so far.

![logo](https://user-images.githubusercontent.com/853712/81464081-a42e8480-9173-11ea-8f51-d588097853f9.png)

I'm almost tempted to commit to using it. What do you think? I've shown it to a bunch of people so far and they think it's great. The arch is obvious with the keystone while staying geometric and simple.

**Comment by sebmck** [comment]
@EduardoLopes This one looks good. I actually spent so long looking at it that after looking at the solid lines in the one above it looked weird.

![Screenshot from 2020-05-08 21-51-11](https://user-images.githubusercontent.com/853712/81464379-0b4d3880-9176-11ea-819e-6bd6290965a1.png)

@jamiebuilds pointed out that the two chunks next to the keystone look too small. Maybe join them and move the other break up a bit like this?

![like this](https://user-images.githubusercontent.com/853712/81464407-68e18500-9176-11ea-9dc6-77612b434410.png)

(Excuse the awful edit. I don't have access to any better image editor at the moment.)

**Comment by EduardoLopes** [comment]
@sebmck 

>What do you think?

I really like it, but i think the font Biryani extra bold is better, because it keeps the width consistent.

And, yeah. it looks a lot better like this. This is the logo already remade with all the metrics consistent.
![02 - Rome - Logo Type - 001](https://user-images.githubusercontent.com/1084297/81465865-b2949480-91a3-11ea-9dbe-61b773cae0cb.jpg)
![01 - Rome - Logo Mark - 001](https://user-images.githubusercontent.com/1084297/81465868-b45e5800-91a3-11ea-84ef-a928a14582d5.jpg)
![Metrics](https://user-images.githubusercontent.com/1084297/81465887-d3f58080-91a3-11ea-9e0f-d64c13c08068.jpg)

I'll need some feedback on kerning. It's the distance between each letter! All letters should look like have the same space between each other. It needs to be done by eye, we can't use metrics to make it look right. But i've been looking at this for too long, i don't even know anymore.

It looks good to me. When i say a logo is done, i like to spend some time not looking at, if i like it after one day, it's good!

**Comment by sebmck** [comment]
Nailed the arch! Looks perfect. I think the kerning there looks really wide. The previous versions look a lot closer which looks better.

**Comment by sebmck** [comment]
Also might be good to try it out with sharp instead of soft edges.

**Comment by ooflorent** [comment]
I agree with the serif font usage, i think it’s better looking. I also like the latest proposal but I’m worried that it could have too much details for low resolution: 16x16 or 32x33 would not have a crispy sharp look.

**Comment by sebmck** [comment]
It’s not uncommon to reduce detail as you scale a logo. I imagine if we needed it that small we would just eliminate the stroke gaps.

**Comment by giuseppeg** [comment]
Just throwing an idea there :) It is simple and can be drawn in the back of a napkin, can adapt do different background colors etc. The font is Euphemia UCAS. FWIW I always regretted not unique, easy to google names for my side projects. ![rome](https://user-images.githubusercontent.com/711311/81468143-07ed9780-91de-11ea-95a0-8b7379178713.png)

**Comment by EduardoLopes** [comment]
Kerning was actually smaller. but i made it even smaller. These are smooth and sharp edges, and smaller versions of the logomark.

![Artboard 13](https://user-images.githubusercontent.com/1084297/81478351-34f87500-91f3-11ea-9f39-3edb96bd0f95.jpg)

16px x 16px lose detail. but looks like chrome and firefox doesn't use 16px x 16px  icons by default  anymore.

These screenshots lose quality when exported, but here's [link 1](http://www.xiconeditor.com/PreviewIcon.aspx?R=299a6c0e-36a6-4b70-ad7a-8c90dd8e51d3) and [link 2](http://www.appsparky.com/?id=aJqcvb) (i know this icon will not be used like this, but anyways)

**Comment by sebmck** [comment]
Nice! I think I prefer a combination of the soft and hard edges. Soft edges for the keystone but hard for the stroke. The hard edges convey accuracy, precision etc more. I think it pairs particular well with the previous serif font which I definitely prefer.

![Untitled-1](https://user-images.githubusercontent.com/853712/81482044-04134280-91e9-11ea-83c1-a3645e88150b.png)

It might also be worth modifying the text shape to make the edges and stroke width more even.

The logomark looks legible at smaller sizes so I don't think that will be an issue either.

**Comment by EduardoLopes** [comment]
I was already getting used to sans-serif. But i like the serif font at lot! At first i choose a serif font because at the front of the pantheon there's uppercase serif letters, and serifs fonts gives me ancient vibes. Maybe people will find it weird, since there's no other javascript logo with serif letters (that we know). It's not common, at least.

Here's side by side:

<img width="1323" alt="Side by SIce" src="https://user-images.githubusercontent.com/1084297/81484121-9f241080-9219-11ea-870d-5854220614f7.png">

I think is not necessary modify the text shape, since it can mess up the balance of the font (i like typography, but i'm not a expert to modify that in a good way). I tried others two fonts, i think the best is the one already shown above. 

Here's sharps edges for the letters too, since there's sharp edges in the symbol

<img width="1645" alt="serif" src="https://user-images.githubusercontent.com/1084297/81483770-0391a080-9217-11ea-84a7-75337f79dee4.png">

**Comment by EduardoLopes** [comment]
Smooth edges on the edges close to the keystone

<img width="1599" alt="02 - Rome - Logo Type - 001" src="https://user-images.githubusercontent.com/1084297/81484169-fcb85d00-9219-11ea-9442-32a94085aa6c.png">

The others edges here, are just a little bit rounded.
<img width="1599" alt="02 - Rome - Logo Type - 001" src="https://user-images.githubusercontent.com/1084297/81484284-bfa09a80-921a-11ea-9b1b-00d9b60d2a94.png">

**Comment by sebmck** [comment]
First one looks good to me! I'm a fan of the hard edges on the bottom but soft on and next to the keystone. If you're happy with it feel free to submit a PR with the source files to the [`assets`](https://github.com/facebookexperimental/rome/tree/master/assets) folder!

Thinking about licensing, would you feel comfortable with the [CreativeCommons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/) license? It doesn't allow commercial usage of the logo and requires attribution for derivatives. You can copy the license text [here](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt) and put it in `assets/LICENSE` if it's good for you.

**Comment by EduardoLopes** [comment]
Looks good to me. I'll prepare the files and send the pull request. 

I need to submit a [CLA](https://code.facebook.com/cla), for this project?

**Comment by sebmck** [comment]
Actually it'd be better to just have it in a new repo. Just created https://github.com/romejs/logo We can always fold it into a new repo later.

**Comment by sebmck** [comment]
Just merged #406 which updates our logo! https://github.com/romejs/logo contains all the design assets. Thank you so much @EduardoLopes!

**Comment by roman-rr** [comment]
Hello everybody, especially logo author! 

I was inspired by this logo works provided and would like ask author to create something similar for my product [cupertino-pane](https://github.com/roman-rr/cupertino-pane)

I will happy to pay or donate some amount in my gratitude, please contact me with email: romwtb@gmail.com

**Comment by roman-rr** [comment]
@MaggieAppleton
Please answer on instagram direct 🤓

**Comment by orta** [comment]
Hi @roman-rr - this is pretty toxic behavior, Maggie hasn't ever posted in this thread and you're asking her to respond to your DMs in public:

![Screen Shot 2020-09-15 at 8 04 47 AM](https://user-images.githubusercontent.com/49038/93208003-dd7e8e80-f729-11ea-8f5e-e4bfd811560d.png)

**Comment by roman-rr** [comment]
@orta Thank you for advice.
