### ISSUE TITLE
ReferenceError: require is not defined when bundle client-side JavaScript

### ISSUE THREAD

**Issue by cavoirom** [facebookexperimental/rome#104]
## Description:

When the dependency uses **require** function, I got error 

    Uncaught ReferenceError: require is not defined

Generated code

    const ___R$$priv$project$...$supports$color$index_js$os = require('os');

The bundle was created successfully but got error at runtime.

## Steps To Reproduce

Error happen when depend project on **axios** module.

## Expected Results

NodeJS API should be exclude from client-side bundle.

**Comment by sebmck** [comment]
Rome doesn't bundle any Node builtins. The bundler is not a focus so I'll close this until we're at the point where we can start supporting and investing in it.
