### ISSUE TITLE
Update TS syntax

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#12]
Since I implemented TypeScript support there has been new syntax added such as `assert` that I've yet to add.

**Comment by sebmck** [comment]
@torifat added `asserts` support. Not sure if there's anything else we're missing.

**Comment by stephenwf** [comment]
Is `import type { ... } from '...'` supported?

**Comment by aarjithn** [comment]
@stephenwf Seems prettier still doesn't support it

https://github.com/prettier/prettier/issues/7263

**Comment by sebmck** [comment]
@stephenwf Ah, it's not actually. We support it for Flow so sharing that logic should be easy. Created #108 to track.
