### ISSUE TITLE
RJSON

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#13]
Rome contains a custom JSON parser at [`packages/@romejs/codec-json`](https://github.com/facebookexperimental/rome/tree/master/packages/%40romejs/codec-json). The primary motivation for building this was `JSON.parse` does not emit detailed information for syntax errors. So I decided to build a vanilla JSON parser with detailed errors that emits Rome diagnostics (#3).

Once I had this built, it was quite easy to add JSON extensions. So I did. They are only enabled when a filename is passed in that ends in `.rjson`, so the parser can parse with and without.

These extensions do not add additional data types and are purely syntactic. When using extensions with a regular JSON file, the error messages will specifically mention it.

The features of RJSON are as followed.

## Unquoted keys

If a property key is a valid identifier then the quotes can be omitted, just like in regular JavaScript.

```
{
  unquotedKey: true
}
```

## Optional commas

Commas are not required to separate elements of an array or object properties.

**Example**

```
[
  1
  2
  3
]
```

```
{
  a: 1
  b: 2
  c: 3
}
```

## Numeric separators

With the addition of [numeric separators](https://github.com/tc39/proposal-numeric-separator) in JavaScript, support has been added in RJSON.

**Example**

```
5_000
```

## Comments

Standard JS comments are supported. Both line and block comments.

The comment support also allows the manipulation of an RJSON file, while retaining comments.

**Example**

```
{
  // Line comment
  /* Block comment */
  foo: "bar"
}
```

## Implicit top level object

Curly braces at the top level aren't required if it's just a list of properties.

Empty input is treated as an empty implicit object.

**Example**

```
foo: "bar"
"bar": "foo"
```

**Comment by Haroenv** [comment]
What is the reason you added no-comma support? Three others are js features, so that makes sense, but I haven’t seen commaless before. Is it to be closer to yaml/rc?

**Comment by sebmck** [comment]
I added optional commas because they can unambiguously be added. I started with just omitting all the syntax I could while still feeling JSONish. Colons could also theoretically be made optional but I feel like that's stepping over "the line".

**Comment by ishpartko** [comment]
> 
> 
> I added optional commas because they can unambiguously be added. I started with just omitting all the syntax I could while still feeling JSONish. Colons could also theoretically be made optional but I feel like that's stepping over "the line".

Why do you need to create another data format when there are formats already familiar to the people? Like .js/.ts/.json/.yaml

It's good when people read about this new format, but usually it's easier for people who work a lot to use the familiar syntaxes.

And it will be easier for code editors, they are more comfortable dealing with familiar syntaxes than with "erroneous json"/ "plain text" in their opinion.

What do you think?

**Comment by sebmck** [comment]
You can already use `.json`. There does not exist a JS parser and stringifier today for YAML or another format that has the ability to retain comments, which I see as the sole motivation for having a custom JSON format.

**Comment by talentlessguy** [comment]
json5 support for configs would be cool too

https://json5.org/

**Comment by sebmck** [comment]
JSON5 does not allow for the reserialization of files and retaining comments. Are you proposing that it be reimplemented?

**Comment by talentlessguy** [comment]
@sebmck

maybe I got you wrong but:

json5 allows making comments

also what does "reserialization" mean?

**Comment by talentlessguy** [comment]
another cool format that I just remembered, Toml

[npm package](https://www.npmjs.com/package/toml) | [toml repo](https://github.com/toml-lang/toml)

I like TOML because online yml or json it is actually readable and simple. Example

```toml
[dev_server]
port = 3000
host = 127.0.0.1
```

**Comment by stephenwf** [comment]
@talentlessguy This I believe: https://codesandbox.io/s/recursing-star-33xfn when you parse you only have the option of getting back an object representation. `consumeJSONExtra` in RJSON implementation keeps the comments.

**Comment by sebmck** [comment]
@talentlessguy 

> also what does "reserialization" mean?

Reading a file, changing something, and then reserializing it back and retaining the original comments. Exactly what @stephenwf said.

**Comment by sebmck** [comment]
@talentlessguy Do you know of any JavaScript tooling that uses TOML? Previously Rome did actually use TOML but after reading https://hitchdev.com/strictyaml/why-not/toml/ and seeing it's extremely limited usage in the JavaScript community I pivoted. I know it sounds contradictory since RJSON is some unique-only-for-Rome JSON, but I would consider syntax omission to not be as big of a deal.

**Comment by sebmck** [comment]
RJSON adds the same syntax extensions as JSON5 except RJSON allows omitting syntax and you cannot use single quotes.

**Comment by sebmck** [comment]
This article resonated strongly and motiviated some of the syntax omission such as top-level curlies etc https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by talentlessguy** [comment]
> @talentlessguy Do you know of any JavaScript tooling that uses TOML? Previously Rome did actually use TOML but after reading https://hitchdev.com/strictyaml/why-not/toml/ and seeing it's extremely limited usage in the JavaScript community I pivoted. I know it sounds contradictory since RJSON is some unique-only-for-Rome JSON, but I would consider syntax omission to not be as big of a deal.

oh I see. As I understood Rome config will be very nested and big, so TOML won't work :/. So we have to use something json-like

**Comment by talentlessguy** [comment]
@stephenwf @sebmck 

hm ok I see that json5 doesn't save comments. But why Rome should save comments in the configuration? Shouldn't they be erased after config consumption?

**Comment by sebmck** [comment]
Rome has the ability to modify the config and then save it. This allows us to have commands like `rome config enable-category lint` and have it load, modify, and save while retaining comments.

**Comment by MrHIDEn** [comment]
> This article resonated strongly and motiviated some of the syntax omission such as top-level curlies etc https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

In that article you mentioned there is HJSON format, very similar to yours RJSON. I agree with you with the idea of RJSON. I believe it is too late for that format but it is interesting thing.
