### ISSUE TITLE
☂️ Website

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#14]
I've yet to start building any sort of website. I'd love for someone else to start building one as it will definitely be needed for our first release.

**Comment by Daniel15** [comment]
Might be a good use case for Docusaurus! cc @yangshun

**Comment by yangshun** [comment]
Definitely, we hope new open source projects within Facebook use Docusaurus as well! @sebmck if you have a list of items that you want/need to have for the website, I can advise whether Docusaurus will a good fit. Sample websites that you want to emulate will be hugely helpful too.

If this proceeds, we can provide dedicated support for the website as well. cc @JoelMarcey @lex111

**Comment by felixhaeberle** [comment]
would love building one! +1 docusaurus sounds really good for the rome! 👍

**Comment by tom-sherman** [comment]
One idea I've stumbled upon recently when creating a docs website at work is to use Hats y and place the typescript types into Gatsby's GraphQL schema.

It's great to be able to use that data in loads of different ways and work from a single source of truth.

**Comment by wardpeet** [comment]
I'm happy to help setup a Gatsby site if this becomes the choice ☺️

**Comment by iFlameing** [comment]
I would be happy to help with anything related to the website :)

**Comment by himynameissebbo** [comment]
Same here, would be happy to help!

**Comment by weblancaster** [comment]
Really good suggestions. Although it's safe to say by looking at the use of Docusaurus for Jest, React Native, Redux and many other projects that its a great option.

@felixhaeberle @Daniel15 I would suggest to setup it up and opening a PR to get it going and going from there.

**Comment by weblancaster** [comment]
After coming back tonight and not seeing any answer, I've decided to get this going since it wouldn't take long. https://github.com/facebookexperimental/rome/pull/62

**Comment by sebmck** [comment]
Update: Thanks to @weblancaster we now have a docusaurus install in the `website` directory! #62

**Comment by sebmck** [comment]
Closing this in favour of more specific issues
