### ISSUE TITLE
Add lint rule for usage of `any`

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#153]

**Comment by KevinKelbie** [comment]
Can I take this? @sebmck

**Comment by sebmck** [comment]
Sure. You will need to add suppression comments to the rest of the codebase though since there are some usage of `any` in very specific places.

**Comment by KevinKelbie** [comment]
Sure thing, just to be clear is this the rule that you want implemented? https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md

**Comment by sebmck** [comment]
Yeah. Just check for all `AnyKeywordTypeAnnotation` nodes, and add `// rome-supress lint/noExplicitAny` to the existing usages.

**Comment by chicoxyzzy** [comment]
It seems that it was implemented and merged so probably this issue could be closed

**Comment by sebmck** [comment]
Yup. Thanks for the ping!
