### ISSUE TITLE
rome init creates rome.json file when prompt is escaped.

### ISSUE THREAD

**Issue by KevinKelbie** [facebookexperimental/rome#161]
Description:

`rome init` creates a `rome.json` file when the prompt asking to use recommended settings is canceled.

## Steps To Reproduce

1. `rome init`
2. hit the `escape` key

## Expected Results

A message like `init canceled` and there shouldn't be a `rome.json` file.

**Comment by sebmck** [comment]
#164 should address this.

**Comment by KevinKelbie** [comment]
fixed in #164
