### ISSUE TITLE
Confusing usage message in init script

### ISSUE THREAD

**Issue by MareikeTaeubner** [facebookexperimental/rome#162]
When starting the init script the user sees this output:

```
ℹ Press space to select an option and enter to confirm
❯ Use recommended settings?
  ◉ Yes
  ◯ No
```

The information message suggests, that you can do something with the space key - directly over a choice where pressing the space key does nothing. If you are missing your coffee in the morning it could take a while to realize that you are not expected to press the space key here at all.

Should the script better guide the user by displaying a fitting message at each choice?

**Comment by sebmck** [comment]
#164 should address this.

**Comment by sebmck** [comment]
#164 merged. Thanks for the report!
