### ISSUE TITLE
☂️ Published Release

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#18]
This issue is to track the milestone [Published Release](https://github.com/facebookexperimental/rome/milestone/1).

Rome is still in development and once we are confident we have something usable and stablefor a wider audience we'll publish to npm.

**Comment by wzalazar** [comment]
all packages will have the same version when you publish or will be independent?

**Comment by sebmck** [comment]
The only package that will be published will be `packages/rome`. All the others are just for internal organization.

**Comment by wzalazar** [comment]
So, Do you consider implement semantic release for that?

**Comment by macovedj** [comment]
Looks like there's already a rome on npm.  Do you know yet how you plan to handle that?

**Comment by sebmck** [comment]
@macovedj I'm the owner of that package. @bevacqua graciously donated it! :heart:

**Comment by diokey** [comment]
Are you targeting a particular timeline for the release or is it just whenever things are ready?

**Comment by sebmck** [comment]
When things are ready. Unclear what that actually means. I can guarantee a release by the end of the month though, even if it's not ready we'll still publish to npm and figure out the remaining gaps.

**Comment by mattsjones** [comment]
Feel like changesets would be a good option for Rome to keep track of release notes over time. 
https://github.com/atlassian/changesets

**Comment by sebmck** [comment]
I'm going to be making another issue to track this.
