### ISSUE TITLE
Will it do versioning/releasing?

### ISSUE THREAD

**Issue by gustavopch** [facebookexperimental/rome#180]
I mean like https://github.com/semantic-release/semantic-release. I'm asking because versioning/releasing is something we must do for every project (either manually or automatically). If Rome wants to provide all the tooling someone needs to create stuff, then perhaps it should also handle that.

**Comment by sebmck** [comment]
Yeah it could. We'll also have the ability later on to build module type signatures, which would be an additional layer of checks for a breaking change.

**Comment by sebmck** [comment]
Closing since the question has been answered.
