### ISSUE TITLE
Create issues for all TODO comments

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#19]
We have almost 100 TODO comments throughout the codebase. Go through these and work out what's still relevant and create issues for the rest. https://github.com/facebookexperimental/rome/search?q=TODO&unscoped_q=TODO

**Comment by vvo** [comment]
Would an app that creates them be useful? https://github.com/JasonEtco/todo for example

**Comment by vickywane** [comment]
How about using other tools to track todos like @vvo has suggested ? 

Like Trelllo or something easily accessible for those who want to contribute so they can jump in right away

**Comment by sebmck** [comment]
I was actually going to close this issue before going public. I looked through the current TODO comments and a lot of them are just notes or not really actionable right now. We can possibly use something automatic once those comments are moved to reduce the noise.
