### ISSUE TITLE
Can't Build Rome on Windows

### ISSUE THREAD

**Issue by Tembocs** [facebookexperimental/rome#215]
Can't build Rome on Windows. I tried to build Rome on Windows as follows.
1. Cloned rome
2. ```cd rome```
3. Run ```./scripts/build-release dist```
4. Got the following error message:

```
ResourceUnavailable: Program 'build-release' failed to run: No application is associated with the specified file for this operation.At line:1 char:1
+ ./scripts/build-release dist
```
I'm on Windows 10 x64 version 1903 build 18362.113.

**Comment by Tembocs** [comment]
I've been able to determine the cause. On Windows we have to be explicit that Node is running the command by doing the following.
```cd rome && scripts/build-release dist```
A pull request has been created for this instructions on the main Rome website.

**Comment by Andrew-Dyachenko** [comment]
I got similar problem.

After issue [#1190](https://github.com/rome/tools/issues/1190), I am trying to work around the problem by building the release myself from the `main` branch, which already contains the required patch, but has not yet been published as **NPM** package. To build release I'm using command `node scripts/build-release dist` at cloned  **rome/tools** project directory However, the project is not building due to unmet dependencies.

**Screenshot:**

![Снимок экрана 2020-12-30 в 12 39 46](https://user-images.githubusercontent.com/10127643/103343401-08081380-4a9d-11eb-9db1-5199ee3ce0e6.png)


**Bash spoiler:**

```bash
MacBook-Pro-Andrey:tools andrew$ node scripts/build-release dist
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@internal/path'
Require stack:
- /Users/andrew/Sites/tools/scripts/_utils.js
- /Users/andrew/Sites/tools/scripts/build-release.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/andrew/Sites/tools/scripts/_utils.js:69:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/andrew/Sites/tools/scripts/_utils.js',
    '/Users/andrew/Sites/tools/scripts/build-release.js'
  ]
}
MacBook-Pro-Andrey:tools andrew$
```

Please tell how to assemble/build release correctly?

**Comment by ematipico** [comment]
Hi @Andrew-Dyachenko , if you want to use Rome straight from `main` you don't need to bundle it at all. Rome is ready to be used as itself. Just the command you need inside your project. 

- checkout rome (`tools` folder)
- go inside your project
- use rome inside your project

```bash
../tools/rome check --apply
```

**Comment by Andrew-Dyachenko** [comment]
@ematipico Thank you you, your hint for starting **Rome** straight from the `main` branch helped, but there were other warning. Should I ignore the warning below if I using `main` branch to launch **Rome** in project directory?

**Warning:**

```bash
! This command has been hidden. Consider its usage to be experimental and do not expect support or
  backwards compatibility.
```

**Screenshot:**

![Снимок экрана 2021-01-03 в 13 11 35](https://user-images.githubusercontent.com/10127643/103476443-b6c29180-4dc6-11eb-9c0c-e1afe0d3765e.png)

**Bash spoiler:**

```bash
MacBook-Pro-Andrey:client andrew$ yarn add https://github.com/rome/tools.git#main -D
yarn add v1.19.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > css-loader@3.6.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > stylelint-config-sass-guidelines@6.2.0" has incorrect peer dependency "stylelint@^10.0.1 || ^11.0.0 || ^12.0.0".
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ rome-root@10.0.4-beta
info All dependencies
└─ rome-root@10.0.4-beta
✨  Done in 28.53s.
MacBook-Pro-Andrey:client andrew$ npx node_modules/rome-root/rome init
 Building trunk 
! This command has been hidden. Consider its usage to be experimental and do not expect support or
  backwards compatibility.

 node_modules/highcharts/package.json:22:19 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Unexpected character :

    20 │   ],
    21 │   "bugs": "https://github.com/highcharts/highcharts/issues",
  > 22 │   "license": "https://www.highcharts.com/license",
       │                    ^
    23 │   "types": "highcharts.d.ts"
    24 │ }

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

× Found 1 problem
Trunk build failure. Exit code 1
MacBook-Pro-Andrey:client andrew$ 
```

**Comment by ematipico** [comment]
Those warnings are there for a reason. You can use those commands but in the future their behaviour can change, just that.

About the error, it's a valid and fatal error. The license is invalid so you'd need to tell Rome to ignore it or fix it with a valid license.
