### ISSUE TITLE
Wrong logo

### ISSUE THREAD

**Issue by carusog** [facebookexperimental/rome#223]
Hi, it looks like you are using a greek helmet in place of a roman helmet for your logo. ☺️

Apart that, maybe something like a styled [Colosseum](https://en.wikipedia.org/wiki/Colosseum) illustration could fit the project better since, first of all it is more iconic for Rome, and, finally, it's related to a "building" tool and it could be a good reference for a solid building.

**Comment by macovedj** [comment]
There's a place where this is discussed over [here](https://github.com/facebookexperimental/rome/issues/1)

**Comment by sebmck** [comment]
From the README:

> Rome has a logo of an ancient Greek spartan helmet. It's not very relevant since it's not Roman, but it looks cooler than a Galea.
