### ISSUE TITLE
regex parser only prints one diagnostic per file

### ISSUE THREAD

**Issue by KevinKelbie** [facebookexperimental/rome#250]
## Description

When you have more than one regex error in a file only the first diagnostic is printed. 

## Steps To Reproduce

1. Create file with the following contents as an example:

```javascript
// test.ts
/[9-0]/;
/[z-a]/;
```

2. `rome lint test.ts`

## Expected Results

There should be a diagnostic for each regexp error in the file. 

## Actual Results

<img width="491" alt="Screenshot 2020-04-05 at 16 58 22" src="https://user-images.githubusercontent.com/19197564/78503477-acebff00-775e-11ea-9433-2d3398885260.png">

**Comment by sebmck** [comment]
Parser errors are purposely deduped to one per line. This is to prevent noisy cascading parser errors. There's nothing specific about this to the regex parser.

Actually after looking into it the unique deduping is commented out and only a max of one diagnostic is produced for `js-parser`. [`JSParser#getDiagnostics`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-parser/parser.ts#L279-L296).

I'm not quite sure what the best behaviour here is. I think we should bail out of linting, and subsequently autofixing, when there's parser errors anyway, at least until we have more confidence in the recoverable parser, or possibly add an `--unsafe-fix` flag.

**Comment by KevinKelbie** [comment]
ah, that makes sense. I'll close this since it seems that its expected behaviour.
