### ISSUE TITLE
removing node_modules

### ISSUE THREAD

**Issue by shirshak55** [facebookexperimental/rome#26]
as node_modules is from history I don't think creating PR is easy . However I think we should add node_modules to gitignore ?

I used the following command to remove entire node modules from git history
```
find . -name node_modules -print0 | xargs -0 git rm -rf --ignore-unmatch
```

I did made a fork which address this issue.
https://github.com/shirshak55/rome/

I think pushing node_module is not intentional right?

**Comment by itaditya** [comment]
in the [Contributing.md](https://github.com/facebookexperimental/rome/blob/master/.github/CONTRIBUTING.md#getting-started) file they have mentioned that they push the node_modules to GitHub intentionally. 

> No dependency installation step is required as we check in our node_modules folder that contains only a copy of TypeScript and some definitions.

**Comment by sebmck** [comment]
Yeah pushing `node_modules` is deliberate. The dependency list is extremely small and only for development. I'll leave this open since I'm sure this question will come up more.

**Comment by tcmal** [comment]
Shouldn't there be a note in the README about the node modules being under a different license? For instance, typescript has its own [ThirdPartyNoticeText.txt](https://github.com/rome/tools/blob/main/node_modules/typescript/ThirdPartyNoticeText.txt)
