### ISSUE TITLE
SSR & SSG

### ISSUE THREAD

**Issue by brillout** [facebookexperimental/rome#271]
Do you plan to support SSR & SSG setups?

E.g. building React views to be executed in the browser as well as:
 1. At runtime in a Node.js server, that is SSR.
 2. At build-time to build static pages, that is SSG.

Neat project btw. :-).

**Comment by sebmck** [comment]
I don't think there's anything that Rome needs to do to support these cases? It's an application framework thing?

**Comment by brillout** [comment]
I just saw that you plan to have a public API #10. Neat.

I've implemented a little SSR/SSG tool ([Goldpage](https://github.com/reframejs/goldpage)) on top of Webpack and more than 80% of the code is about circumventing Webpack shortcomings.

Depending on how Rome's public API is designed, SSR/SSG could be implement-able with only a couple hundreds of LoCs, which would be a thrilling little piece of code to write.

You seem to greatly care about design and well-thought abstractions. The JS world has been a mess and it's lovely to see people care about cleaning it up.

**Comment by brillout** [comment]
> Depending on how Rome's public API is designed, SSR/SSG could be implement-able with only a couple hundreds of LoCs.

FYI I've done that in https://github.com/brillout/vite-plugin-ssr thanks to Vite's SSR support.

> I don't think there's anything that Rome needs to do to support these cases? It's an application framework thing?

Vite has APIs tailored towards SSR, which makes the life of SSR tool authors dramatically easier, which leads to flourishing SSR ecosystems.

Would be neat to have a similar plugin in Rome's world. (Btw if someone is interested in this, feel free to hit me up on Twitter/Discord.)
