### ISSUE TITLE
Rigid IDE integration

### ISSUE THREAD

**Issue by brillout** [facebookexperimental/rome#283]
I appreciate that Rome is rigid in areas where flexibility is futile, such as your intent to make linting fully inflexible.

I'm curious if you considered to go as far as applying the same principle to IDE integration? E.g. having a vscode Rome extension that is fully opinionated. Rome could go as far as even creating its own (strongly opinionated) modal editing, e.g. https://github.com/johtela/vscode-modaledit. With TypeScript, this could lead to some interesting super-powered editing experience.

Same as linting, vscode Rome extension would be opt-in and users are free to use neovim, emacs, etc.

I can see many people wanting to volunteer; the barrier of entry for contributing is low.

AFAICT the added workload on Rome core would be low.

Thoughts?

I can't wait to see Rome liberating us from trivialities.

**Comment by sebmck** [comment]
We actually have an implementation of the [LSP](https://microsoft.github.io/language-server-protocol/) and  VSCode extension that was implemented in #207. The only special sauce that's in the VSCode extension is finding the Rome binary and then executing it. You should be able to use any other editor that supports LSP and it just needs to run `rome lsp` and connect over stdin.

Right now I don't think there's any additional planned functionality beyond what the LSP already provides, but we could do some interesting and powerful things with our diagnostics format as it's significantly richer than what the LSP offers.

**Comment by sebmck** [comment]
Closing since the question has been answered. LSP will be the implemented protocol. LSP additionally allows custom methods which we could expose for additional functionality.
