### ISSUE TITLE
Leading comments on export statements are not attached properly

### ISSUE THREAD

**Issue by ooflorent** [facebookexperimental/rome#293]
Leading comments on export statements are not attached properly.

## Steps To Reproduce

Considering this file:

```js
/* LEADING */
export {/* INSIDE */ FOO} from './bar';
```

The comments are attached as expected:

```
Program {
  directives: Array []
  comments: Array [
    CommentBlock {
      id: '0'
      value: ' LEADING '
    }
    CommentBlock {
      id: '2'
      value: ' INSIDE '
    }
  ]
  body: Array [
    ExportExternalDeclaration {
      leadingComments: Array ['0']
      source: StringLiteral {value: './bar'}
      namedSpecifiers: Array [
        ExportExternalSpecifier {
          exported: Identifier {name: 'FOO'}
          leadingComments: Array ['2']
          local: Identifier {name: 'FOO'}
        }
      ]
    }
  ]
}
```

- `LEADING` is attached to `ExportExternalDeclaration`
- `INSIDE` is attached to `ExportExternalSpecifier`

However, if `INSIDE` is removed:

```js
/* LEADING */
export {FOO} from './bar';
```

Then `LEADING` is attached to both nodes, which makes formatting way more complicated since the specifier is tokenized before the declaration.

```
Program {
  directives: Array []
  comments: Array [
    CommentBlock {
      id: '0'
      value: ' LEADING '
    }
  ]
  body: Array [
    ExportExternalDeclaration {
      leadingComments: Array ['0']
      source: StringLiteral {value: './bar'}
      namedSpecifiers: Array [
        ExportExternalSpecifier {
          exported: Identifier {name: 'FOO'}
          leadingComments: Array ['0']
          local: Identifier {name: 'FOO'}
        }
      ]
    }
  ]
}
```

## Expected Results

In the last example, `LEADING` must be attached only to `ExportExternalDeclaration`.

**Note:** It works as expected for import statements!

**Comment by sebmck** [comment]
I think this has something to do with us converting `ExportLocalSpecifier` into a `ExportExternalSpecifier`, and when we do the comment attachment, we correctly try to remove the leading comment from the specifier, but since we've cloned the node it has no effect.
