### ISSUE TITLE
Build from source?

### ISSUE THREAD

**Issue by EverlastingBugstopper** [facebookexperimental/rome#30]
Would love to help out with some documentation on building from source - if you can point me in the right direction I'm happy to make a PR 😄

**Comment by sebmck** [comment]
There's two scripts that are relevant. [`dev-rome`](https://github.com/facebookexperimental/rome/blob/master/scripts/dev-rome) and [`build-release`](https://github.com/facebookexperimental/rome/blob/master/scripts/build-release).

When running `dev-rome` it compiles Rome then immediately runs it with the arguments passed. This is used when you're actually developing against trunk. eg. `scripts/dev-rome --help`

`build-release` takes a directory argument and generates what will eventually be the npm release. eg. `scripts/build-release dist`

**Comment by EverlastingBugstopper** [comment]
👍 thanks
