### ISSUE TITLE
There is no node_modules folder in the .github folder

### ISSUE THREAD

**Issue by aligoren** [facebookexperimental/rome#32]
Hi :)

I was reading the **Getting Started** section in the contributing documentation.

In the below line mentioned about **node_modules** folder.

> No dependency installation step is required as we check in our node_modules folder that contains only a copy of TypeScript and some definitions.

I clicked it but as you can see there is no .github folder. I think [this](https://github.com/facebookexperimental/rome/tree/master/node_modules) is the new location of the **node_modules** folder.

**Comment by sebmck** [comment]
Not sure why that was a link in the first place. The `CONTRIBUTING` file was originally in the root but was moved into `.github` which caused the incorrect reference. Thanks for the report!
