### ISSUE TITLE
Optional Chaining Autofix

### ISSUE THREAD

**Issue by macovedj** [facebookexperimental/rome#337]
So currently the linter identifies optional chaining and fixes it by simply getting rid of it as depicted below.
BEFORE:
`const foo = {bar: 'baz'}; console.log(foo?.bar)`
AFTER:
`const foo = {bar: "baz"}; console.log(foo.bar)`.

Is there a reason that the linter should get rid of optional chaining?  If so, then it should fix to `foo && foo.bar` so that there isn't a lost null check.  If not, then the linter should not take issue with optional chaining.

**Comment by ooflorent** [comment]
There was an issue in the formatter that was omitting the optional chaining operator. It has been fixed a few hours ago. Could you try using the latest commit?

**Comment by macovedj** [comment]
Oh cool.  I tried with the latest and the issue disappeared.  Thanks!
