### ISSUE TITLE
problem: rome run index.js

### ISSUE THREAD

**Issue by chrcatalano92** [facebookexperimental/rome#393]
Description:

I have the rome version 0.0.2 and I have a problem run: rome run index.js
To boot I used rome.json in Sublime

rome.json:
{
  "version": "^0.0.2",
  "lint":{
  	"enabled": true
  }
}

## Steps To Reproduce

 C:\Users\User\hello-world\rome\my_existing_project>rome run index.js

 rome.json:4:3 parse/json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Unknown enabled config property at lint

    2 │   "version": "^0.0.2",
    3 │   "lint":{
  > 4 │    "enabled": true
      │    ^^^^^^^^^
    5 │   }
    6 │ }

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

× Found 1 problem

1. 2.

## Expected Results

Why do you find me a problem?
I look, kindly, for your answer. Thanks

Yours sincerely

**Comment by sebmck** [comment]
Remove the lint object, it’s enabled by default now. Did you find these instructions on the website?
