### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by linvain** [facebookexperimental/rome#40]
Please describe the actual usage of the package

> Its amazing how there can be such a long readme file and it still does not communicate what this actually does...
— https://news.ycombinator.com/item?id=22430940

**Comment by smbkr** [comment]
Given the state of the project (early stages, experimental and subject to change), I think the README is pretty clear already.

**Comment by olee** [comment]
Just a small list of getting started steps for a kinda hello world project built with rome to test it would be much appreciated.
This project looks super awesome and I would really like to try it out without having to dig through the project first to understand how to use it.

**Comment by sebmck** [comment]
I specifically wrote the README with the current target audience of Rome, which are contributors already familiar with the project. I'm unsure how to actually make it clearer without maker it longer. I'm happy to accept PRs that make it clearer if anybody has specific suggestions.

**Comment by sebmck** [comment]
I've opened #55 with some basic usage instructions. As said before, I'd welcome any contributions that make the purpose of the project clearer.
