### ISSUE TITLE
Where are the configuration options?

### ISSUE THREAD

**Issue by jloleysens** [facebookexperimental/rome#43]
Playing with `dev-rome` a bit the documentation seems to only go one level deep; listing the commands that are available on `./scripts/dev-rome --help`. Specific help for subcommands was not present and so I ran into 👇🏻 quite quickly.

```
Couldn't find a rome.json or rome.rjson or .rome.json or .rome.rjson for
    /my/cool/project/path
```

The following would be really helpful (to me, a totally random new user 😅):

1. A way to get docs for sub-commands
2. Some kind of indication of how to interact commands (`./scripts/dev-rome config --help`)
3. A pointer to config options and how to hydrate a new project

Seems relevant to https://github.com/facebookexperimental/rome/issues/7

**Comment by bhargavgana** [comment]
hi,
Rome project config exist as rome.json or rome.rjson files. It can also in the  rome property, in package.json.

**Comment by sebmck** [comment]
#55 will add some documentation.

**Comment by diokey** [comment]
It looks like this PR https://github.com/facebookexperimental/rome/pull/165 will improve CI output include subcommand help and examples
