### ISSUE TITLE
Codebase structure

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#5]

**Comment by Ayudh** [comment]
@sebmck can you provide any docs/video on understanding the existing codebase. I am trying to figure out the flow of code, but failing. If possible, please provide any docs on the major construct of the codebase so that the code can be familiarised.

**Comment by sebmck** [comment]
Nothing like that exists. Writing technical documentation is hard and I do not have the time at the moment. I would recommend reading previous PRs. The codebase is massive and it depends on what you want to do. I am available in the Discord server to answer any questions and provide code references if you are trying to achieve something specific.
