### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by arslivinski** [facebookexperimental/rome#50]
There's a plan to make Rome a package manager too? This way the only external dependency would be the Node itself.

**Comment by sebmck** [comment]
Tentatively, yes. Rome already parses `package.json` files, as well as normalizing and validating them. There also exists hooks in the module resolver for fetching packages that don't exist. This would be very long-term functionality though and need to be done very deliberately to avoid disrupting the JS package management ecosystem.

**Comment by adrianhasna** [comment]
I don't think there is a benefit in doing this. 
There are great package managers already and long term may split the rome's community and direction: folks who use rome as a package manager, and folks who use it as a companion tool (as intended I guess).
Also we're trying to minimize the API here.

**Comment by aarjithn** [comment]
Actually, rome already supports pulling in packages from url's which is kind of approach deno is also following. Doesn't that make rome a full fledged package manager?

**Comment by sebmck** [comment]
It does I guess. I was thinking more about managing packages from npm though which is essential for Node development and what most people think of as a package manager.

**Comment by sebmck** [comment]
Closing since the question has been answered.
