### ISSUE TITLE
The Roman Empire was a violent empire run by dictators

### ISSUE THREAD

**Issue by alexanderwallin** [facebookexperimental/rome#53]
## Description

Rome was the capital of the Roman Empire, a society run through dictatorship, slavery and violence. Your etymological trivia refers to proverbs that seem innocent but refers to slavery and assimilation.

Sure you could argue about the technicalities of what you're actually referring to, but that's irrelevant. No matter your intensions, the profile of this project is of white ruling and conquest. You can pick a much better one, one that isn't offending or reeks of white peoples' historical ignorance, one that conveys union, cooperation and solidarity rather than wartime colonialism and oppression.

## Steps To Reproduce

Rename this to something that refers to American slavery and ask for feedback.

## Expected Results

Outrage.

**Comment by vinayakkulkarni** [comment]
**facebookexperimental**/rome

**Comment by intercaetera** [comment]
Not even sure if this is trolling.

**Comment by sebmck** [comment]
I don't think the way this issue has been presented will lead to a productive discussion so I am closing and locking. The logo issue #1 is of relevance as the usage of a soldier's helmet as the current logo is contentious.
