### ISSUE TITLE
Project config file - minimize API

### ISSUE THREAD

**Issue by adrianhasna** [facebookexperimental/rome#65]
One of the project goals is to minimize the API, but right in the getting started guide, we see the project configuration "can take three possible forms": rome.json, rome.rjson or "rome" entry in package.json. 
Already too many options. Is there a case where a project won't have a package.json!?

IMHO we should stick to "rome" entry in package.json.

**Comment by eddiemonge** [comment]
package.json can and already is already pretty crowded. Minimizing the API to me does not mean limiting the choices in how to do configuration, but in having less configuration.

**Comment by sebmck** [comment]
>  Already too many options. Is there a case where a project won't have a package.json!?

Yes. You can have subprojects with different settings. `package.json` also doesn't allow comments which is one of the greatest advantages of RJSON #13.

**Comment by maraisr** [comment]
I'd like to echo @adrianhasna comment and say, the simplicity nature of this project doesn't really articulate its own message. rjson seems very complicated compared to standard json. Having multiple ways of defining things, with or without quotes, root level object etc... 

Now I personally don't mind which form wins out - however, these three forms thing has to turn into "this is how you configure it" approach.

> You can have subprojects with different settings.

You can do this with package.json now `"private": true`

**Comment by talentlessguy** [comment]
I don't think this is a good idea because a lot of people are used to config files instead of putting everything to package.json

importing either json from the config or package.json won't make a huge difference. Both can be supported, it won't lose much in performance (as I think)

**Comment by sebmck** [comment]
Also in favor of removing `package.json` and having only `rome` in `package.json` and `rome.rjson`.

**Comment by milesj** [comment]
Please no config in `package.json`, it's the most restrictive format. Hell, even JSON is an awful config format.

**Comment by sebmck** [comment]
@milesj Hence RJSON #13. I don't see a problem with allowing people to put it in there if they want, especially if the config is only very small.

**Comment by Janne252** [comment]
I think I would prefer having support for `*.js` configuration file as some options might be useful to resolve at runtime, like checking custom command line arguments. Some tools even have support for a default exported async function that resolves the configuration.
