### ISSUE TITLE
Unable to enable linting

### ISSUE THREAD

**Issue by rzig** [facebookexperimental/rome#69]
Hello! I have created a new project and added rome as a dependency. Here's my `package.json`:
```json
{
  "name": "myproject",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "rome": "node ./node_modules/rome/bin/rome"
  },
  "author": "rzig",
  "license": "ISC",
  "devDependencies": {
    "rome": "file:../rome/dist"
  }
}
```

The file in `src/index.js` is just one line, `console.log("Hi");`.

I am able to successfully run `npm run rome compile src/index.js`, but running `npm run rome config enable lint` fails with the following:
```
✔ Setting lint to true in the project config rome.json
✖ Error occured while testing new project config. Your changes have not been saved.

 rome.json:2:10 json ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected object at lint

    1 │ {
  > 2 │   "lint": true
      │           ^^^^ 
    3 │ }

 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

When I manually update `rome.json` and run `npm run rome lint src/index.js`, I get 
```
rome.json:2:12 json  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected object at lint

    1 │ {
  > 2 │     "lint": true
      │             ^^^^ 
    3 │ }

 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

I'm guessing the reason that the second step of `rome config enable lint` fails is because rome is setting `lint` to `true` when it should actually be an object?

**Comment by sebmck** [comment]
Looks like the command should actually be `rome config enable-category lint`. So the config should be:

```
{
  "lint": {
    "enabled": true
  }
}
```

**Comment by sebmck** [comment]
We should add some special cases to the root objects if they're booleans since this seems like something someone would also write organically

**Comment by rzig** [comment]
I can make a PR to change the error message outputted by the CLI then, currently it tells users to run the old command.

**Comment by rzig** [comment]
I went ahead and created a PR. Right now `rome config enable-category lint` doesn't seem to be actually modifying the file, but there's a good chance it may be on my end - I'll open a new issue if necessary.
