### ISSUE TITLE
Add ignore property to format project config

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#74]

**Comment by bsotodo** [comment]
@sebmck I would like to take a look at this. If tha's ok, could you please point me in the right direction? Otherwise I can work on something else

**Comment by sebmck** [comment]
@bsotodo Quite a few files would need to be updated. It's not really for the quaint of heart.

- Project loading: [`packages/@romejs/project/load.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/project/load.ts): You would need to go to the block that has `categoryExists(format)` and copy+paste the same `ignore` property handling that you see for `config.lint.ignore`. 
- Linter glob: [`packages/@romejs/core/master/linter/Linter.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/core/master/linter/Linter.ts)
- `format` command: [`packages/@romejs/core/master/commands/format.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/core/master/commands/format.ts): Add a callback to `getFilesFromArgs` so that `project.config.lint.ignore` can be customized by [`packages/@romejs/core/master/commands/format.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/core/master/commands/format.ts) to use `project.config.format.ignore`.
- `WorkerAPI.lint`: [`packages/@romejs/core/worker/WorkerAPI.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/core/worker/WorkerAPI.ts): Update so that formatting is skipped when ignored. Add a `format` property in the parameters of `handler.format` to indicate if formatting should take place
- Make a subtype `LintRequest` in [`packages/@romejs/js-compiler/api/lint.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-compiler/api/lint.ts) with a `format` property, and disable formatting when it is `false`.
- Pass in the `format` property to `js-compiler.lint` in [`packages/@romejs/core/common/fileHandlers.ts`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/core/common/fileHandlers.ts).

**Comment by bsotodo** [comment]
Thanks! I'll give it a try.
