### ISSUE TITLE
Semver Parsing error for versions which are NPM aliases 

### ISSUE THREAD

**Issue by zinyando** [facebookexperimental/rome#79]
Description:

I'm trying to bundle a node hapijs app and running into an issue where versions which are npm aliases are failing. 

## Steps To Reproduce

  Try bundling a basic `hapijs` server. It's getting stuck in the `package.js` file of one the dependencies on `"@hapi/joi-legacy-test": "npm:@hapi/joi@15.x.x"`

![Screenshot 2020-03-01 at 18 04 20](https://user-images.githubusercontent.com/806774/75629096-d8bc1800-5be7-11ea-8c2e-1c20accff8f6.png)

I'd be glad to create a fix if you point me in the right direction.

**Comment by sebmck** [comment]
Thanks for the report! Fixed in #85.
