### ISSUE TITLE
AST

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#8]
The Rome AST is derived from [estree](https://github.com/estree/estree) but with some pretty significant changes. Contained here are notes that may be useful when working with it.

- Redundant AST nodes have been eliminated. Some of these exist in estree to provide additional location information eg. `ClassBody` but it has been eliminated in favor of putting the `body` array on the parent.

- The entire AST is fully strongly typed and type definitions can be found in [`packages/@romejs/js-ast/
`](https://github.com/facebookexperimental/rome/tree/master/packages/@romejs/js-ast/). This makes it relatively easy to follow and will exist as canonical documentation.

- Flow and TypeScript nodes are prefixed with namespaces.

- Effort has been made to reduce ambiguity in the AST, ie. `Identifier` has been split into [`AssignmentIdentifier`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/patterns/AssignmentIdentifier.ts), [`BindingIdentifier`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/patterns/BindingIdentifier.ts) and [`ReferenceIdentifier`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/expressions/ReferenceIdentifier.ts).

- If multiple AST node types share properties then it's been abstracted into another node. For example, [`ClassExpression`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/classes/ClassExpression.ts) and [`ClassDeclaration`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/classes/ClassDeclaration.ts) both have a [`ClassHead`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/classes/ClassHead.ts#L22) property. This makes it easy to convert between the two by just retaining the `head`.

- This is more notable with [`PatternMeta`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/patterns/PatternMeta.ts) which is set on pattern node types.

- Object keys have a dedicated node in the form of [`ComputedPropertyKey`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/objects/ComputedPropertyKey.ts) and [`StaticPropertyKey`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/objects/StaticPropertyKey.ts). These are shared amongst [`ObjectProperty`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/objects/ObjectProperty.ts), [`ClassMethod`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/classes/ClassProperty.ts) etc. This makes it very easy to share logic.

- Similarly, [`MemberExpression`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/expressions/MemberExpression.ts) has a [`ComputedMemberProperty`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/auxiliary/ComputedMemberProperty.ts) and [`StaticMemberProperty`](https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-ast/auxiliary/StaticMemberProperty.ts) property.

**Comment by andersekdahl** [comment]
Is there anything written down around your thoughts/plans on AST transformation?

I'm particularly interested in interop with how Typescript does it or getting access to type information during AST transformation. There's a lot of interesting optimization that's possible when you have access to `ts.TypeChecker` that is either really hard, or much less robust without it.
